name: Setup Rust
description: "This action sets up Rust"
inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.8"
runs:
  using: "composite"
  steps:
    - name: Checkout chroma-hnswlib
      uses: actions/checkout@v3
      with:
        repository: chroma-core/hnswlib
        path: hnswlib
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
